# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [5]:
print(np.__version__)
np.show_config()



1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
a = np.random.rand(2, 3, 5)
print(a)

[[[0.39320613 0.30442302 0.24146347 0.7326115  0.356225  ]
  [0.28612514 0.13275076 0.35386385 0.12504081 0.73165136]
  [0.79773897 0.24024406 0.04748676 0.02193018 0.88671474]]

 [[0.77121177 0.25484891 0.56731946 0.48116049 0.57925483]
  [0.06439044 0.44598228 0.35337917 0.76553085 0.14090293]
  [0.18086318 0.85437798 0.07201122 0.89811904 0.32523417]]]



### 4. Print a.


In [7]:
print(a)

[[[0.39320613 0.30442302 0.24146347 0.7326115  0.356225  ]
  [0.28612514 0.13275076 0.35386385 0.12504081 0.73165136]
  [0.79773897 0.24024406 0.04748676 0.02193018 0.88671474]]

 [[0.77121177 0.25484891 0.56731946 0.48116049 0.57925483]
  [0.06439044 0.44598228 0.35337917 0.76553085 0.14090293]
  [0.18086318 0.85437798 0.07201122 0.89811904 0.32523417]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [15]:
b=np.ones((5,2,3))


### 6. Print b.


In [16]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [19]:
print(a.size)
print(b.size)
if a.size==b.size:
    print("same size")
else:
    print("notta same size bruv")

30
30
same size



### 8. Are you able to add a and b? Why or why not?


In [ ]:
print(a+b)
you cant coz different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [27]:
c=np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [31]:
d=c+a
print(d)
#coz same shape

[[[1.39320613 1.30442302 1.24146347 1.7326115  1.356225  ]
  [1.28612514 1.13275076 1.35386385 1.12504081 1.73165136]
  [1.79773897 1.24024406 1.04748676 1.02193018 1.88671474]]

 [[1.77121177 1.25484891 1.56731946 1.48116049 1.57925483]
  [1.06439044 1.44598228 1.35337917 1.76553085 1.14090293]
  [1.18086318 1.85437798 1.07201122 1.89811904 1.32523417]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a,d)
d=a+1

[[[0.39320613 0.30442302 0.24146347 0.7326115  0.356225  ]
  [0.28612514 0.13275076 0.35386385 0.12504081 0.73165136]
  [0.79773897 0.24024406 0.04748676 0.02193018 0.88671474]]

 [[0.77121177 0.25484891 0.56731946 0.48116049 0.57925483]
  [0.06439044 0.44598228 0.35337917 0.76553085 0.14090293]
  [0.18086318 0.85437798 0.07201122 0.89811904 0.32523417]]] [[[1.39320613 1.30442302 1.24146347 1.7326115  1.356225  ]
  [1.28612514 1.13275076 1.35386385 1.12504081 1.73165136]
  [1.79773897 1.24024406 1.04748676 1.02193018 1.88671474]]

 [[1.77121177 1.25484891 1.56731946 1.48116049 1.57925483]
  [1.06439044 1.44598228 1.35337917 1.76553085 1.14090293]
  [1.18086318 1.85437798 1.07201122 1.89811904 1.32523417]]]



### 12. Multiply a and c. Assign the result to e.


In [35]:
e=a*c



### 13. Does e equal to a? Why or why not?


In [44]:
a==e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [49]:
d_max=np.max(d)
print(d_max)
d_min=np.min(d)
print(d_min)
d_mean=np.mean(d)
print(d_mean)

1.8981190358452857
1.0219301844563966
1.4135354146887706



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [51]:
f=np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [54]:
f[d==d_min]=0
f[d==d_max]=100
f[d==d_mean]=50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
print(f)

[[[ 25.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  25.   0.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  25. 100.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [55]:
print(d)
print(f)

[[[1.39320613 1.30442302 1.24146347 1.7326115  1.356225  ]
  [1.28612514 1.13275076 1.35386385 1.12504081 1.73165136]
  [1.79773897 1.24024406 1.04748676 1.02193018 1.88671474]]

 [[1.77121177 1.25484891 1.56731946 1.48116049 1.57925483]
  [1.06439044 1.44598228 1.35337917 1.76553085 1.14090293]
  [1.18086318 1.85437798 1.07201122 1.89811904 1.32523417]]]
[[[ 25.  25.  25.  75.  25.]
  [ 25.  25.  25.  25.  75.]
  [ 75.  25.  25.   0.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  25. 100.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [57]:
f[d==d_min]="A"
f[d==d_max]="B"
f[d==d_mean]="C"
f[(d > d_min) & (d < d_mean)] = "D"
f[(d > d_mean) & (d < d_max)] = "E"
print(f)

ValueError: could not convert string to float: 'A'